-- ============================================================================
-- REVENUE BREAKDOWN BY INDIVIDUAL (AM & MGS)
-- Last 6 Months (May 2025 - October 2025)
-- ============================================================================


-- ============================================================================
-- QUERY 1: Get AM Merchant IDs
-- ============================================================================


-- ============================================================================
-- GET MERCHANT IDs FOR AMs (including Hsin Tsi Lim)
-- ============================================================================

SELECT 
    am_name,
    COUNT(DISTINCT merchant_id_nk) as merchant_count,
    LISTAGG(DISTINCT merchant_id_nk, ', ') WITHIN GROUP (ORDER BY merchant_id_nk) as merchant_ids
FROM ocd_adw.d_merchant
WHERE city_id = 13
    AND country_id = 1
    AND am_name IN (
        'darren@grabtaxi.com',
        'suki@grabtaxi.com', 
        'chiayee@grabtaxi.com',
        'hsintsi.lim@grabtaxi.com'
    )
GROUP BY am_name
ORDER BY merchant_count DESC;



-- ============================================================================
-- QUERY 2: Revenue Breakdown: Teoh Jun Ling
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Teoh Jun Ling (MGS)
-- Last 6 Months (May 2025 - October 2025)
-- ============================================================================

WITH teoh_jun_ling_merchants AS (
    SELECT merchant_id_nk
    FROM (VALUES '1-C4B1BA22JX5XLE',
        '1-C7ADVKMYMAD3TX',
        '1-C7BUJLJJHGAJJA',
        '1-C4CBT6A1A4E3TX',
        '1-C6JERYKCNP6CNN',
        '1-CY4BJ4CCGNMVCT',
        '1-C63FEF6WLTEBN6',
        '1-C62BAVLCSFXJRN',
        '1-C7BDSELTNPLXAA',
        '1-C4CBRKUFTBCALX',
        '1-CZEXHFV1RBUVCJ',
        '1-C2UHGA3HLYXJTA',
        '1-CYVVJGKZV2MGN6',
        '1-C22DJNLFVPJFBA',
        '1-C3KWRJLKRELCHA',
        '1-C22EPAA2N3V1G2',
        '1-C2VDGJ3HTX2JNN',
        '1-C3TBA3DHRAJ1CN',
        '1-C32TSE4ANNXAVN',
        '1-C7EEDFBAEPMYVE',
        '1-C7BENXJZRYMEL2',
        '1-C4BECJWEKFE2PE',
        '1-C3W2VCNZEEUYE6',
        '1-C32UNJJGGKJ2R6',
        '1-C23HHFKJBBMXAN',
        '1-CZJGMBTZNP5KLN',
        '1-C4CBRKUFTNTBGA',
        '1-CZEWG8C2LFJGL6',
        '1-C2XCJYNFJZNTVA',
        '1-C2JYRANELB43NA',
        '1-C3D2RF2HAPUXNN',
        '1-C36GTP2UEJMUJJ',
        '1-C2NCVCBHRTECE6',
        '1-C2XBMEX3VBXZKE',
        '1-C2UBENKJJYCAGX',
        '1-C65KGJECR6AVC6',
        '1-C4NVMELUDGDCAX',
        '1-C2AKJFAYT7MVTA',
        '1-C7MJWEM3NF3ACX',
        '1-C23CANXEEKT2J6',
        '1-C3TBA3DHN3CWNN',
        '1-C3WJG6W1VVKTHA',
        '1-C2UBEGKHJFA2V2',
        '1-C6XFKBVYEGBTEJ',
        '1-C6UFRKTDCVDFVA',
        '1-C26HTPXCGNDUEE',
        '1-C7A3HANZDE5YJT',
        '1-C3TGG4JAARBXT6',
        '1-C62YR2XDTTCDTN',
        '1-C6NAR2LHG3UHEA',
        '1-C3E2GY2DT243NT',
        '1-C7DWRBBGRBTCNN',
        '1-C2XAPENZJNMVE2',
        '1-C7CYRLLGGUBBPA',
        '1-C2TDR4BEALMXAN',
        '1-C34XCXAWR4DCME',
        '1-C2BVLCMKNNCHCA',
        '1-C2THE8KXBGKGJT',
        '1-C34ZLNUWRCACT6',
        '1-C2WGV23HNEMEJ2',
        '1-C7CJSEWUJUEGWA',
        '1-C2KFCJ2WAK5DLA',
        '1-C6MKBCBYMFXFSA',
        '1-CZJFAXDUKBTUGX',
        '1-C3KKEPTZGLN3FA',
        '1-C33AKCLUKEAGA2',
        '1-C6T2CYCWNAXCCA',
        '1-C7CCN63KREDBJX',
        '1-C4B2N3LXT4AJFA',
        '1-C3EELCLYG4KTNA',
        '1-C26WVZAULKNEGE',
        '1-C3ECCN6XLTMVTE',
        '1-C25GCXXJCAXAGT',
        '1-C3UAVPXART3DRE',
        '1-C6CTGN2ZSCBHTJ',
        '1-CZCGR2NZTB6WDE',
        '1-C6CEJ3KZVPLBDE',
        '1-C6CTJ3XULFLXFE',
        '1-C2MKWBJ3J35DC6',
        '1-C22CWAWXVNNTCN',
        '1-C7A1RP5KLTDTAA',
        '1-C3NHDAM2VPNAGA',
        '1-C35CNAUGAXXUTT',
        '1-C6XZRNAGNP5ARN',
        '1-CZLKAUNTSCCZNJ',
        '1-C4L2CVNGCCC2RT',
        '1-CY6EN7THCLCWC6',
        '1-C6UDFEC2CEKCL2',
        '1-C65GLCL3ALLYNE',
        '1-C2DJEBWEEUCBN6',
        '1-C66HFA6HAFU1HE',
        '1-C3MERBEJLLBZAE',
        '1-CY43NU3CSF4DE6',
        '1-C3UBVUDYUGAJNA',
        '1-CZKHC8J1EVEXEN',
        '1-C2EHTFL1GT4AAA',
        '1-C22CVFLZNPNKFA',
        '1-C6VAKBXTA76JCJ',
        '1-C63CPBVVLJT2TA',
        '1-C24JR3EETUKYEE',
        '1-C3EGCNDKT3L3GX',
        '1-C6WURUM2CFJVGE',
        '1-C3WVBAEVNRJ1RN',
        '1-C2XAPEKJC3JJGJ',
        '1-C2NYTRKCN6MZME',
        '1-CYLBTCAFN74JC6',
        '1-C32XHAK2R4LFR6',
        '1-C2BERJNZV2UUE2',
        '1-CZD1A7NASAJ3GX',
        '1-C2DXV6WCJK6CFE',
        '1-C3MEWE21RT4DA6',
        '1-C2WKCZKJUAW3JX',
        '1-CZDEDB6FERB1LT',
        '1-C23DL8KJKF62L6',
        '1-C36ZGX2EFGCAVE',
        '1-C4EGVX3ZJY2TRA',
        '1-C3VFAUEZCA6TJ2',
        '1-C6CHVY3WA7ADBE',
        '1-C64ATF5BUFM2EE',
        'MYDD12690',
        '1-C4KKJEEEWBWYJJ',
        '1-C62AEJDXGJKFV6',
        '1-C651BFJBEABKEA',
        '1-C3NCAUE2ERMFVT',
        '1-C2LJJRN3N3NYFA',
        '1-C4EEL3UHLGCCUA',
        '1-CY3YJ2JCR8NZDA',
        '1-C4KHEAJYPFMJJT',
        '1-C2EBRLEJNPJTJX',
        '1-C3L1DE2BUGJASA',
        '1-C4EGGX3YHE61R2',
        '1-C4MYDCMBGA3URA',
        '1-C2U3AFMBRBEKEN',
        '1-C6VAJ2DACJLTVX',
        '1-C22TVT6GAJWGFA',
        '1-CZKCDEAUSCADLJ',
        '1-CZDYLJ62G33VJJ',
        '1-C2VXNFKTR73YBA',
        '1-C2WXTZNHCY41GA',
        '1-CZAXC7KHC2WEAJ',
        '1-C3EHVX3FCBEJAA',
        '1-C3UFKBKGE2EYEJ',
        '1-C22ZC6DUA7BVV6',
        '1-CYVFTENUSF5CR2',
        '1-C3LUAP4KL7XHPE',
        '1-C2KXRGMFCCDALN',
        '1-CYV1R8MZBB4KWE',
        '1-C6VXDCNUNTKBTX',
        '1-C24BCCJUAE23KE',
        '1-C6WZUE4XBAWXNE',
        '1-CYNEATVWGLLTTA',
        '1-C4JWGTXFLBUAJN',
        '1-C7BYRRAZEZDYNA',
        '1-C7ABGZBJGUKTVJ',
        '1-C6XKSFEYRXWHRX',
        '1-C6VKUE3ART5EME',
        '1-C2DXBFNWL8NWGX',
        '1-C6WJA2NDVY5UTT',
        '1-C3XZCF3HA7C3G2',
        '1-C23JJ6AEFB6UNA',
        '1-C2WYT33JATEALJ',
        '1-C6B2E2KERF5HKE',
        '1-C6NYRAKFVP3TNJ',
        '1-C6AJC7W1G74GAA',
        '1-C2E1GFDBTT5EBE',
        '1-C4EWARAZE62KNA',
        '1-C7CJSEWVAFLZHA',
        '1-C3NXGCJ3MCLYRX',
        '1-C7DEDCMYMBTYL6',
        '1-C6AKATKKAYBENA',
        '1-C65JE7TXGYAEG6',
        '1-C3NZRJDKE7AARJ',
        '1-C3VAA7WUJZMVCX',
        '1-C7AVG7B1HCJVJ2',
        '1-C24CA6CGCYWUUE',
        '1-C7KCVNDZAU5FRN',
        '1-CZMZNA5JDFM3VJ',
        '1-C3KWN62EJ6EYRE',
        '1-C32KA3J1DBLZPA',
        '1-C6KGHENDL3EFEN',
        '1-C32BLLDFJGDXLT',
        '1-C4D2HBUEVJAVVA',
        '1-C4KVA721CXADNJ',
        '1-C7DVCJWFKECEMA',
        '1-C3AFWF3TLALXCJ',
        '1-C2T3CY31AREXLA',
        '1-C26FFEX1RAKFTT',
        '1-C62HARBFJCKDGE',
        '1-C22TTZNHJPCAJN',
        '1-C6NYSGJXE3TCHE',
        '1-C66XCY6TRJTHPA',
        '1-C62CTRBXRKJXNJ',
        '1-C2DWGXJBSED2BA',
        '1-C6T3NBMTA7LTKA',
        '1-C65JETB1N34EEJ',
        '1-C63FVE5JGKVAAX',
        '1-C33HC2EYTXDZJ2',
        '1-CZKTLRA1GXAWBE',
        '1-C7MWUA2GNAJJN6',
        '1-C2TYAETJSCBYME',
        '1-C7C3ANWXJYMTCJ',
        '1-C26BTVEGPF5ZLE',
        '1-C3XFSF2XABD1LE',
        '1-C62YSGJAR24ZGX',
        '1-C7A3J73WNTU2NX',
        '1-C2U2EEKJMCBFEA',
        '1-C2UBENLZTK6JN2',
        '1-CY3KJJAGRPTASE',
        '1-CYUURJEAEZNTPE',
        '1-C6WHDBMTHBMEN6',
        '1-C62WCN4ZGBJAGN',
        '1-C2K1A2A2R7B2JA',
        '1-C7AWFFWHA26FWA',
        '1-C3EXAALVKEJXT6',
        '1-C3XWRTEZN7EASE',
        '1-C7LFJTVBG7KCC2',
        '1-C26ZKCJTT2TBPE',
        '1-C6XYTJWZC4EUVE',
        '1-C2DWC3JXLRC3TN',
        '1-C66WLEBWRUEGCJ',
        '1-C2CTA6UZACLXCN',
        '1-C7AFJKW3V2KFLE',
        '1-C242G3E2EVDFJX',
        '1-C26ZKCJTTP3HLJ',
        '1-C64KJJLHVYC3CJ',
        '1-C4DXVTKEVF6VAT',
        '1-C3MEAJJAENXZLA',
        '1-C6AHVKC3AYMCAX',
        '1-C36AUBKKLNTJAN',
        '1-C3KXNCDUL241WE',
        '1-C63WVBK1UGMHJJ',
        '1-C36CNP3JLLLUCA',
        '1-C7AFNB5BAKKXLN',
        '1-C6MFKBVKMF2GNX',
        '1-C6D1AY5DJPBWA2',
        '1-CZJHELN2CEM2SA',
        '1-C34ACXATLJ5WTX',
        '1-C7AGFEMUCJUXAA',
        '1-C6A3GVNBAXJGGX',
        '1-C7NGV7MHPFBESA',
        '1-C3BUAE3YJ2XJT6',
        '1-CY6EN7THA25KCE',
        '1-C4JDNEWXRAAURX',
        '1-C6JZGUNTBGMYV6',
        '1-CZD1EEKZTEK1TE',
        '1-C63AVB2TL4LWEA',
        '1-C32WNEWZSAAVC6',
        '1-C6TZDF5YAJ2KN6',
        '1-C2WEAEKJLJLYJE',
        '1-C3CKVVECV7EVEE',
        '1-C23KBGMHLEWZJ6',
        '1-C6EUTBXHNYC2GT',
        '1-C3WKGJD2T6UWLJ',
        '1-C7ECLGCHAN6WPA',
        '1-C2EHTFL1E7DJAX',
        '1-C2WEJNKJE4JKC6',
        '1-C7LKPENWL2CUE2',
        '1-C2NYA7C2LZJWTA',
        '1-C36FCNW1JZNFHE',
        '1-C22ZV4ACUF6XLA',
        '1-C6WKCTKZNBLZLX',
        '1-CY2HTKVFUABTLJ',
        '1-C23HGEKJUF5CVA',
        '1-C6W2JTMFNEBDTJ',
        '1-C7DZJNBFRACWG2',
        '1-C4J1ENMAVCAERN',
        '1-C7CBTUJ3AU3JDE',
        '1-C7C3AB2VUGACGT',
        '1-C3BFSFUJVJ6WRT',
        '1-C7KFRNEHLX2WCJ',
        '1-C3JCRATJCLMULJ',
        '1-C26FAX3JLP6XR6',
        '1-C23EL23KDCKATJ',
        '1-C64WRF5VEXKTVT',
        '1-C6JZC32HJGA2ET',
        '1-C4MYGJNBC7LZE6',
        '1-C7AFMAVFRBAWFE',
        '1-C3LBJEX1V7XDGX',
        '1-C3LTUAJTNBC3LJ',
        '1-C25AT2KKVN5BCN',
        '1-C6AWGAM3EZEDJX',
        '1-C4KXRVM1RFVBVJ',
        '1-C3KWNFBWNFTCR6',
        '1-C3BARPTAHEJCA6',
        '1-C2VEGCCCKEVGVJ',
        '1-C66YE7B3JXJUAN',
        '1-C7ADRJL3GJAGAN',
        '1-C3LALLEEG35ZT6',
        '1-C2KDKFNEFBCCVE',
        '1-C4BZVRAGL7XXEE',
        '1-C3L1CY4TJ3VWLT',
        '1-CZDBLUWELNVXL6',
        '1-C7CYJ733AN52E6',
        '1-C33WJP3TT6TGJ6',
        '1-C24AC6XFN7TVV2',
        '1-CZAYAAEXE7BCKE',
        '1-C7LYR22ZN7VEME',
        '1-C6TUWB3GV63GKE',
        '1-C2XHGLJCV8CZE6',
        '1-C362VUKDJ6UZJ2',
        '1-C62JTBKTA6D3BA',
        '1-C7KZRJA3LRBKLA',
        '1-C6KYUFB2C7JKR2',
        '1-C65CGUMTNXJDCX',
        '1-C26DJ6EZVJACWE',
        '1-C4DWG6EEG7AGJX',
        '1-C25WDFXGVY5ENT',
        '1-C7KXJKUFTXDEFA',
        '1-C26FFEX1REXFEN',
        '1-C6VHJJLTTCDHRT',
        '1-C7MAVN5KSAAECN',
        '1-C25ELCJXVXX2NT',
        '1-C3KDJVMVFF52KA',
        '1-C7BJVZAXLYWBBA',
        '1-C26HNJLDHAAUEJ',
        '1-C32GNNAGGE6DNT',
        '1-C7EFVLLWTBXCJA',
        '1-C7EDDF5TGUCVE6',
        '1-C2UHSA41LXUCHA',
        '1-C7KVMEDAEEBKAE',
        '1-C221N2AVJKAUGN',
        '1-C7JKC3LYJ3EXNT',
        '1-C7MXCVMGEPUDEE',
        '1-C6TGRTNZCAE1GT',
        '1-C64FCE5GRUCGRN',
        '1-C2BWNUJHLA4AN6',
        '1-CYLYRN2XN7BYVT',
        '1-C7BENRBUNA2DRT',
        '1-C7AER8KVGF5DGN',
        '1-C65JJ3MXJJKYNA',
        '1-C2LHRBACEJABRA',
        '1-C7CJNKNBLLETKA',
        '1-C6T2UBTGCTEZVA',
        '1-C2VUJPKJETXZET',
        '1-C7A3JBXJDAM1NE',
        '1-C4LXJ3MXT3AJME',
        '1-C6JXETBFDA3YAJ',
        '1-CZDHSEEZLJCGLX',
        '1-C22GJ8KJEZJAGE',
        '1-C3MAG2JXV63WET',
        '1-CZJ2NJEENTAKC6',
        '1-C7KCAUCVE6DWLE',
        '1-C6T2UF5KV3BTJE',
        '1-C6DVCAWAJLLDAT',
        '1-C65DC66ZT7TVV2',
        '1-C2WXTACKJ4CURT',
        '1-C7DUECKURCDYEE',
        '1-C4A3NY4TCKLWR2',
        '1-C23WLALJE6AZNX',
        '1-C62CTRBXRKBAPA',
        '1-C23HEFVGGJWDFA',
        '1-C6DWN25GGJLVR2',
        '1-C3EBAF4ULPVVR2',
        '1-C3KAR2EHN7AVV2',
        '1-C2U1EBAKWAMEE6',
        '1-C4KYLYWKKFDFN2',
        '1-C7ETA6XANVBFEX',
        '1-C2THE8KXE6KCT6',
        '1-C66XGVE2J24FRE',
        '1-C7CVFAKHTAMJJA',
        '1-C7LJAXCTT3ECNX',
        '1-C4AERX2WA26DLJ',
        '1-C6XXVF5ZE8KYCA',
        '1-C3ETJ2EYRAEXFE',
        '1-CYLZPCJAEGA1ME',
        '1-C65ALN3GCNU3C2',
        '1-C3ETJP3GHFLDTJ',
        '1-C4DVLGBVFCAVR6',
        '1-CY6YWEN1BALBNJ',
        '1-C3DGHE2YJXLFFE',
        '1-C3WKHAE3V7JBJA',
        '1-C4AUTCJJT3T3EE',
        '1-C7JWPFKFTAEGT6',
        '1-CZDKECDXEZLER6',
        '1-C2WWJ33JLJ5VJX',
        '1-C25EKBJDUA5AGN',
        '1-C341LJUEA231RX',
        '1-C3X1DBEZMB52LX',
        '1-C7EFVPCVVTNEEX',
        '1-C2UBGK4YMATTCX',
        '1-C6XVEBN2LCEUUE',
        '1-C661TTVUAX3XRN',
        '1-C7LFL8BBBFWZTA',
        '1-C6UCJAVYVJTVTJ',
        '1-C6MCVBVFGTEETX',
        '1-C7BKMAKDRJCDNJ',
        '1-C32AKBD1SEWJNA',
        '1-C7LGJX3YCKXHAX',
        '1-C4MZANKUCBVYL6',
        '1-C4AGN2KBAXVCSA',
        '1-C66FR7XTAJUUJX',
        '1-C3TCTFXAATBFNE',
        '1-C7KZRJAAEZC2LT',
        '1-C3X1VLDUSA31UE',
        '1-C4CFN2JDJT4CJX',
        '1-C4LYJNUKAAEBT6',
        '1-C4KWSFB3EF6FR2',
        '1-C6TFT3MZHFUCGE',
        '1-C3CYV2LHT35DAN',
        '1-C6XXVLJ3BAV2T2',
        '1-C7CWVLC1UB21HA',
        '1-C66JG24XRRCXCX',
        '1-C36AUF3YGBCUT6',
        '1-C7C2BAM1R3CJGT',
        '1-CZKWWE2DC2AJKE',
        '1-C3XKCUJYGUCFHA',
        '1-C3X3L6X1J6L3TA',
        '1-CZMTFCLJCCDJBA',
        '1-C25ZG73YV6CHMA',
        '1-CY5FNLDVECKVPA',
        '1-C7ETFFTXG36WVJ',
        '1-C4CKJBJBRUWZLJ',
        '1-C3LXL3EUA2TJNT',
        '1-C25UELJCG3EHCJ',
        '1-C7DVCY5EJ6U3JJ',
        '1-CYLZPCEYLAU2EE',
        '1-C6V3LUJBFA4WNA',
        '1-C7MTPCDETULGTT',
        '1-C7BKRALVVY6TJX',
        '1-CZKDTBVUTJDWEA',
        '1-C22VG64CCUEAFA',
        '1-C3UHTP2GJXWBV6',
        '1-C4CESBKXAECGVJ',
        '1-C24JCXWWV24TLN',
        '1-C35XR3LJFF6UTN',
        '1-C7CWAX5CRTTJTX',
        '1-C7JGJYBTE7DEVX',
        '1-C6KWGXACV7T2RA',
        '1-C2WXJ23JJYWFVX',
        '1-C7DUA3XUWFDKR6',
        '1-C2UFGJ3HL64AA6',
        '1-C4BFNN42DBNFE6',
        '1-C66HG3K2A3MKCE',
        '1-C2XBHB3HWADHVT',
        '1-C6TFWBNVTNX2GE',
        '1-C2KYG2UAJTLDEE',
        '1-C3CXDGAELX6DWA',
        '1-C6CHAJJVR25VV6',
        '1-C4AFAFXZEUAEV2',
        '1-C32TRNW2V3B2CE',
        '1-C6AUN2LJENJBRX',
        '1-C63VC3NFT26FTT',
        '1-C2UFELJ2L7BGUE',
        '1-C2XXGELXCJ6WAT',
        '1-C3JCR2EDNP43NA',
        '1-C7CYR32ZR7KGE6',
        '1-C7AWEFJAGPBTVT',
        '1-C3DKRLJJJNAZME',
        '1-C23EN7DTGBJAWE',
        '1-C2TBSCDUE7MXG6',
        '1-C7AERX3GCX2XGX',
        '1-C7NJLUNJG6CAGE',
        '1-C4B3MCNJCJCYT6',
        '1-C6LAFGCUVGLVG6',
        '1-C4BETLKDLJDWNE',
        '1-C23HEFUAWAXYLJ',
        '1-C2KYG2UAE3WET6',
        '1-C64HLKEUCK2FR2',
        '1-C242FALYVTUWNE',
        '1-C3TKN4DVTZBWUA',
        '1-C362AY2JNALVRJ',
        '1-C3VDJ62AVJ4CLN',
        '1-C7BENAKAVE2GL2',
        '1-C3LTV731VVLUJA',
        '1-C25VWE3BNKVUEX',
        '1-C3WCRCEBJ8D2E2',
        '1-C6DTCUKDJXEHKE',
        '1-C36HNX23JAEDKA',
        '1-C65EVTTTGN2EL2',
        '1-C3XXJ2ECJUUTVN',
        '1-C26YG6WTCXWURX',
        '1-C6NWCJE3R73VJA',
        '1-CZJTTKDWRX2BVA',
        '1-C33WJE6AA3MJGE',
        '1-C65XJT3GV2UHCX',
        '1-CZEYJBCEKEU2JX',
        '1-C6XFG3TKJ353EN',
        '1-C653LF4DG8M1GT',
        '1-C7CXAE22EGMBR2',
        '1-C63JREB1R24YGE',
        '1-C2MTBEKATZBUSA',
        '1-C3VHT3LKAFKXG2',
        '1-C24WC4E1LXM1E2',
        '1-C64GT76CVUJTEA',
        '1-C3XFN8AVNUUFTJ',
        '1-C3D2GZACVNAYTX',
        '1-C4EKRE6FEB3WAJ',
        '1-C7CHRP6CG8LXJA',
        '1-C6DGCLC2NJWVEE',
        '1-C7MYALAGDAA2UA',
        '1-C2DYTRCJTX31ME',
        '1-C36GVY3DTNTKWA',
        '1-C2VYNVCGNBB1AX',
        '1-C4ADEF3WLE6TNT',
        '1-C6JDV73ZRYCFRX',
        '1-C7AEPE52G4NXJJ',
        '1-C65WNXUVDCJBLE',
        '1-C2XHNXKKC3BXGE',
        '1-C4LVALNJAPCBHE',
        '1-C6WWKBVKNJ4JCA',
        '1-C4AADAJ2AXXXL6',
        '1-C24BCN2DL36DDE',
        '1-C62KLECVRRNWNX',
        '1-C7KZAPJFNX6XLA',
        '1-C7EGNTN1EUDTG6',
        '1-C7CDJTTDEXBBCT',
        '1-CZJTRAEYMFVBR2',
        '1-C3XETCBAEF53JN',
        '1-C3EEPCMAAALJGT',
        '1-C7ADTLNTRJ3CAE',
        '1-C6NYPEN2TUTZJN',
        '1-C26KLTVTNA4ECA',
        '1-C25YN4JUBEKXWE',
        '1-C2MHKE4ZLRJDUE',
        '1-C7ABEXEECY5EUA',
        '1-C3WBRVJTTVA1JA',
        '1-C23BDEKKJY6DFA',
        '1-C7KCVFXXC7B1RE',
        '1-C6MUJFTZBCDBR2',
        '1-C4CBG3WAAUCXL6',
        '1-CZB2WCD2J3MTLA',
        '1-C4ABGCKTEYTXLN',
        '1-C7LTR6DXVAVART',
        '1-C63YKCDJHE5EJN',
        '1-C34BFFXKRKBUV6',
        '1-C65DCVEGA7UDGJ',
        '1-C7CCNE6CNPKHUA',
        '1-C7MKUE3VNVA3AA',
        '1-C2AAL8CYEJTKDA',
        '1-C7LUJJAHNJTATE',
        '1-C3B2TE3DAXNHL2',
        '1-C4L2KF3FLJ33SA',
        '1-C7CJSEWULJEVSA',
        '1-C7DVSE6YJXAGRX',
        '1-C3UJR2EFSFVKL2',
        '1-C242KBXUGEVWET',
        '1-C35EJCMZT2UJNT',
        '1-C63JLF3XCFVJLJ',
        '1-C4DXC73KEJ5AVE',
        '1-C35ELGB3LAADGJ',
        '1-C65ZEN3UC4E1CT',
        '1-CZAWEKTYNFUYAT',
        '1-C4KHTXLXHBCUSE',
        '1-C222L23JTNVAL6',
        '1-C7ACBCMTRAEXGT',
        '1-C62ZJCLUNNXHV6',
        '1-C32ZBFXDRN5GAX',
        '1-C2L3LBW2TPL2LT',
        '1-C7DVWBMGRGMYPE',
        '1-C3CZR743CX5AKE',
        '1-C63CJ4NCN7WUJX',
        '1-C7CYRTKETEWGN6',
        '1-C261GF23AEWKVE',
        '1-C65BGVJWUABYAT',
        '1-C7CJNAKCAKT1CN',
        '1-C661TTVTV72ECT',
        '1-C36GTE2ZG2DHRE',
        '1-C2THE8KXJ243N2',
        '1-C65JLFLDRNMHKA',
        '1-C62HAKM1PA5WG2',
        '1-CZB2WCD2JUMAL2',
        '1-C7CYR8MGDFB1RT',
        '1-C7BYTN23DAU1UE',
        '1-C3KHN2EJLFCHHE',
        '1-C63FGKVENLACLX',
        '1-C7AULY3ZELBGE2',
        '1-C3E1KA6JRKT1LN',
        '1-C6XKTTUYN6CUL2',
        '1-C4B2N3LXTTCGN6',
        '1-C4JYLE5AG74FCE',
        '1-C2XWSFKJBABGHE',
        '1-C6NYRP4CJ4DHLA',
        '1-C2CZVT4DHBAXLJ',
        '1-C3NTAEXACBUXCN',
        '1-C2B1VVKHVKVYWA',
        '1-C6WCCY3TUEE2T6'
    ) AS t(merchant_id_nk)
),
-- 1. COMMISSION REVENUE (from deliveries/dine out)
commission_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.commission_from_merchant, 0) 
            ELSE 0 
        END) as commission_revenue,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.gross_merchandise_value, 0) 
            ELSE 0 
        END) as gmv,
        COUNT(DISTINCT CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN f.order_id 
        END) as orders
    FROM ocd_adw.f_food_metrics f
    WHERE f.city_id = 13
        AND f.country_id = 1
        AND f.business_type = 0
        AND f.date_id >= 20250501
        AND f.date_id < 20251101
        AND f.merchant_id IN (SELECT merchant_id_nk FROM teoh_jun_ling_merchants)
    GROUP BY CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 2. ADS/SPOTLIGHT REVENUE
ads_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(accrued_amount_before_tax_local, 0)) as ads_revenue,
        SUM(COALESCE(billable_ad_spend_local, 0)) as total_ads_spend,
        SUM(COALESCE(mex_prorated_billable_ad_spend_local, 0)) as mex_ads_spend
    FROM ocd_adw.agg_ads_merchant
    WHERE date_id >= 20250501
        AND date_id < 20251101
        AND merchant_id IN (SELECT merchant_id_nk FROM teoh_jun_ling_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 3. MEX FUNDED CAMPAIGN REVENUE (spending)
mex_campaign_spend AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(total_mex_promo_spend, 0)) as mex_campaign_spend,
        SUM(COALESCE(total_grab_promo_spend, 0)) as grab_campaign_spend,
        COUNT(DISTINCT merchant_id) as merchants_with_campaigns,
        COUNT(DISTINCT order_id) as campaign_orders
    FROM ocd_adw.f_food_discount
    WHERE city_id = 13
        AND date_id >= 20250501
        AND date_id < 20251101
        AND booking_state_simple = 'COMPLETED'
        AND is_mfp = TRUE
        AND merchant_id IN (SELECT merchant_id_nk FROM teoh_jun_ling_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- Combine all revenue sources
combined_revenue AS (
    SELECT 
        COALESCE(c.month_id, a.month_id, m.month_id) as month_id,
        COALESCE(c.commission_revenue, 0) as commission_revenue,
        COALESCE(c.gmv, 0) as gmv,
        COALESCE(c.orders, 0) as orders,
        COALESCE(a.ads_revenue, 0) as ads_revenue,
        COALESCE(a.total_ads_spend, 0) as total_ads_spend,
        COALESCE(a.mex_ads_spend, 0) as mex_ads_spend,
        COALESCE(m.mex_campaign_spend, 0) as mex_campaign_spend,
        COALESCE(m.grab_campaign_spend, 0) as grab_campaign_spend,
        COALESCE(m.merchants_with_campaigns, 0) as merchants_with_campaigns,
        COALESCE(m.campaign_orders, 0) as campaign_orders
    FROM commission_revenue c
    FULL OUTER JOIN ads_revenue a ON c.month_id = a.month_id
    FULL OUTER JOIN mex_campaign_spend m ON COALESCE(c.month_id, a.month_id) = m.month_id
)
SELECT 
    month_id,
    'Teoh Jun Ling' as person_name,
    'MGS' as role,
    commission_revenue,
    ads_revenue,
    mex_campaign_spend,
    (commission_revenue + ads_revenue) as total_revenue,
    gmv,
    orders,
    -- Calculate percentages
    ROUND(commission_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as commission_revenue_pct,
    ROUND(ads_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as ads_revenue_pct,
    -- Additional metrics
    total_ads_spend,
    mex_ads_spend,
    grab_campaign_spend,
    merchants_with_campaigns,
    campaign_orders
FROM combined_revenue
ORDER BY month_id;



-- ============================================================================
-- QUERY 3: Revenue Breakdown: Hon Yi Ni
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Hon Yi Ni (MGS)
-- Last 6 Months (May 2025 - October 2025)
-- ============================================================================

WITH hon_yi_ni_merchants AS (
    SELECT merchant_id_nk
    FROM (VALUES '1-C653LBNKR73ZEA',
        '1-C3XUVX4CNB2UVX',
        '1-C6MXVBVBSCKTTN',
        '1-C22VJYWZFCLAVA',
        '1-CZKKUETTN34BAX',
        '1-C6XENCM3GGDGLN',
        '1-C2NCCP5AWBUTJE',
        '1-C6AWDAUBNNUBG2',
        '1-C6L1NVJJKFTDVA',
        '1-C7AAHBNVEF2CDA',
        '1-CZNUAUVYN6XHCJ',
        '1-C7BDTABYCLDVKE',
        '1-C3VHR4JTCP2WJT',
        '1-C3DGGUJUJKMYTN',
        '1-C6CTLKLZTTBJVE',
        '1-CY61NKMVBCEAJX',
        '1-C2XCAEKHVXCHBA',
        '1-C4KKJUMVE36VTA',
        '1-C6DWTTWTC65VPE',
        '1-C2VUG23JTKBKDA',
        '1-C7D1GTCUAEACTJ',
        '1-C4NCC232L332CN',
        '1-CY61NKMVG7JZAA',
        '1-C3DJTBLWWFDUTN',
        '1-C63HPCJXNFWFDA',
        '1-C3XAT7WHCKMYVE',
        '1-C2U2JRKJANDJGA',
        '1-C6AGEN4BLZBTJJ',
        '1-CZDDCUNTCYVXDA',
        '1-C23ZRBDCNADHJN',
        '1-C23EN2K2NPXHT2',
        '1-C6CZGN6XCFNTLT',
        '1-C22VA3WBNJKKSA',
        '1-C3TGEBBFEEXJRA',
        '1-C6VXCTLZEX4GET',
        '1-C6NBR4JTEKNBRA',
        '1-C65XLFBGJXNDR6',
        '1-C4L1T2NGMEEAME',
        '1-C4DDAE32VJ5JTA',
        '1-C3UVVKDHLGL1TA',
        '1-C7MWV4A3GJ3CG2',
        '1-C3U3WADTGECARN',
        '1-C3VZJNXTENWALJ',
        '1-C4AANE5AT2LYJT',
        '1-C22YCFCZG62ZGX',
        '1-C2VGHCEZT73BR2',
        '1-C6VXG4NTELDEAA',
        '1-C3XVPFXGG2EFGX',
        '1-C6A1PE4WFAVEAA',
        '1-C25ZN3EZGJVHKA',
        '1-CZL3VATJN24ZWA',
        '1-C2UGC24YUANXJX',
        '1-C33XUCKXAELECA',
        '1-C3LFWBE2WBMJDA',
        '1-C4DBWAJWJALJNT',
        '1-C33KRTKHLNK1TT',
        '1-C4MAJ3TTCZJCCJ',
        '1-CZLAGTUAJNCHEJ',
        '1-C6CKLYACGUXEDA',
        '1-C2MVJ7CGJNXYRT',
        '1-C26YNKDYDAU3L2',
        '1-C26TJLJ3VCBFJA',
        '1-C2T2G7LYRFUABE',
        '1-C3EXAE3HJ2TWLE',
        '1-C4MZCXJGKEUZV6',
        '1-C2LGL7J1PE51NA',
        '1-C2LHRBACATCAKE',
        '1-C3KCN4EUAEBYLJ',
        '1-C3LHNFXWELBCLA',
        '1-C4EGFFCDEELGUE',
        '1-C4JDLK4ZPFTYJA',
        '1-C65KGLMXUE6GA2',
        '1-C2J3C3ATMGCWEX',
        '1-C3WJLFW3JN4KN2',
        '1-C7JDVZMAFF51C2',
        '1-C24ULE2TGUTDGN',
        '1-C4CCCCMYSBBGN6',
        '1-C6WURUM2BAAHRN',
        '1-CZECG2VZLN5VKE',
        '1-C3KEELJJVPEUHA',
        '1-C2VCT8KKL7VVN2',
        '1-C33HCVLUMEN1AA',
        '1-C3CJDBE1L66YRN',
        '1-CYLJTJC1VED1G6',
        '1-C3LHLYXEGXKWJJ',
        '1-C6LHEJXBCJDUGE',
        '1-C4CUN2CXRCBEAX',
        '1-C2T2GRLZBB2UAA',
        '1-CZJWLAXGGCBYG6',
        '1-C4CTVTECWA4EN6',
        '1-C3WAR7XYCN6HA2',
        '1-C3BWJE3UJJ3FPA',
        '1-C2XFN2A3N36AAE',
        '1-C6BJWF2XC2N2NX',
        '1-C2BAJFNVVU5VAT',
        '1-C2DJTANEAAMELE',
        '1-C2BXELMYA6JZG2',
        '1-C25ZNTKEDB5DWA',
        '1-CZL3VATJPGCYAJ',
        '1-CY5EN3NYTXEAVJ',
        '1-C2JVUA2HJYTVE6',
        '1-C6VHL6JYJYBHL2',
        '1-C2KCNFA1EAABEA',
        '1-C6K3JECGLBLVAE',
        '1-C2UGTJ3JGYJHEA',
        '1-C2U2J3AYLRLACT',
        '1-C6TBME5VL73DE6',
        '1-C2DHGNMJEE41ET',
        '1-C3BWLCEJGX3UAN',
        '1-C2LAR6J3GJXEGE',
        '1-C4BKWEVEA6D3L2',
        '1-C6NHTTUFRYTTVA',
        '1-C2DWGXJCAPDVSA',
        '1-C2EVCJTJAN23GJ',
        '1-C6KVME5JT6BFVA',
        '1-C4JTJ2XFTUAGVX',
        '1-C7C3CTBBGTKZG2',
        '1-CYWBWBDHGBTWN2',
        '1-C2VELXN2DACBJA',
        '1-CY4BJ4CCFFABV2',
        '1-C7ETA2VVVJLGFA',
        '1-C6TAPFA1G7CVDA',
        '1-C3DJC4N3MFLAAJ',
        '1-C3LFTNAGTTLCCT',
        '1-C3LXMCJAJ2NBCN',
        '1-C2VCV23JAPMBLJ',
        '1-C3JKJUEBDGN2GT',
        '1-CZDEUCDAR25GRE',
        '1-C2WZHA5FLKK1TE',
        '1-C6XCVTNGRFNYNX',
        '1-C7CCLXXEKBATHA',
        '1-C3XFFA3GMANAG2',
        '1-C32XJX3WMFLHTA',
        '1-C23KN2DEVT6EJT',
        '1-C2KCJPJCRKAJAJ',
        '1-C35DG6ADR22BRE',
        '1-C62KLECVRRNHAE',
        '1-C2LGL7K2T24KG2',
        '1-C3MTT2EYNREBRE',
        '1-C6VETTKDV3KCEN',
        '1-C24UNCDDWELUEE',
        '1-C24VGBETBANET2',
        '1-C4L3TYBVHBBGNX',
        '1-C32UL6WHT3KKE2',
        '1-C2KDKFNEEK5FLE',
        '1-C6WUPBVWKA5XG2',
        '1-C4A3NJ5AEUJTGN',
        '1-C2JUGZDKTFUDTX',
        '1-C4EFLVKZAJ5EG2',
        '1-C6WWGYDWLNTWGX',
        '1-C7BDSEJZJ7WGAT',
        '1-C2THVYDDUFUCAJ',
        '1-C4EGFAMTEANELN',
        '1-C4MZUF3ULKE1DA',
        '1-C6X1KF6ET6M1SE',
        '1-C33VMBMDV6W1J2',
        '1-C7DAA2U3NNBWKE',
        '1-C22KT26VFBACVE',
        '1-C2LHRBABTUUVJX',
        '1-CZJWLAXYCFKCJJ',
        '1-C662KCL1APBAGA',
        '1-C6T2C8AAN8KXTX',
        '1-C3XUVTTCFB5ZVJ',
        '1-C2VGAPLZMB3XGE',
        '1-C3LHJ2E3G662CA',
        '1-C4LXJ751NVMVWA',
        '1-C2W2PB3JUACZLX',
        '1-C2VZJRL3EVDXTE',
        '1-C3WASCJTMGADT6',
        '1-CY6DUA3CPEXCGT',
        '1-C7AHC74GL8BTME',
        '1-C3WKFBKGGAJKLE',
        '1-CYLHSE3GTCNVME',
        '1-C7AWHFBWNBLHNJ',
        '1-C35UC3JXG2XTN2',
        '1-C2NJVALTEPJAKE',
        '1-C24WGE21A23GWE',
        '1-C36XL3JUV4JGCA',
        '1-C7EZC4JTTZEATJ',
        '1-C32ZTX2UEKN2VJ',
        '1-C6WYBEW1N3LTT2',
        '1-C2VFGBKJGNXXRN',
        '1-C3KEC4M3LFCKDA',
        '1-C7CVETLWLF5FHA',
        '1-CZDEDB6FEJMHC2',
        '1-C3NYVYAWL63DFE',
        '1-C7JKCTJZFBKWEA',
        '1-C2WGKFKJEBXJCN',
        '1-C7JGRXXBLTLHWA',
        '1-C4EFG7DJMB4FR6',
        '1-C25DLAKFA6E3LE',
        '1-C23JCFKKA62ACJ',
        '1-C3BBMATBREL3HE',
        '1-C24AFAEVEU3KA2',
        '1-CZJAE32CE4KUSA',
        '1-C6TZDF5XNJATE6',
        '1-C7C3CBMWVUUYGN',
        '1-C3TCA2JCN6XKCT',
        '1-C3MKGKEHVNLCHA',
        '1-C6LCTFWFWA5DRX',
        '1-C2KEGXCHCJTJN6',
        '1-C4NJVZBVJUKZLE',
        '1-CZM1KA4TC35JE6',
        '1-C2EUJZA2ARA2LN',
        '1-C35TJ4JWRA22N6',
        '1-C3BURTCJAP2VNT',
        '1-C4DGJY5BVXT1EN',
        '1-C64ARY22E343C2',
        '1-C6KBCUJYGCKJRJ',
        '1-C26YLTKYJY3ZLA',
        '1-C4DXA3N1GJAHTN',
        '1-C2VFWB6JPF2DTT',
        '1-C62WV7ACA7ETDE',
        '1-C33BV3K1V32KL6',
        '1-C7BKNLMHCPX3TX',
        '1-C6AGGX5KLALTJN',
        '1-C4DVKFEHKABUN2',
        '1-C2VXPGKJLU5JEX',
        '1-C2WWTF2EEX5FCX',
        '1-C25EG3THSBEZNE',
        '1-C2VDGAAZKAU3AE',
        '1-C23YGKCUVEWECE',
        '1-C7BJVCKGTJDVC2',
        '1-C4KWUCEYVCEVJX',
        '1-C24BETETJGJZGX',
        '1-C7LWCUTKJLEGA6',
        '1-C23EPA5CJUCTAT',
        '1-C4NZBE5VDCLTVN',
        '1-C6WBJFEXNUWGRA',
        '1-C3UBTAEEVBAZRJ',
        '1-C3EVCTKHL4CBAN',
        '1-C4D1LN4AGYAUUE',
        '1-C25ASCKTTBEWE6',
        '1-CY4XJBL1CBVWLN',
        '1-C3NEN6W3HFWDFE',
        '1-C2KEV2ACJ7TWAE',
        '1-C3BHJKK3JAAFRX',
        '1-C7AVGP6WRY2ZMA',
        '1-C35EKE53G7WAEJ',
        '1-C7BYNF3HMEXVCE',
        '1-C3NJCF2KV7ACNN',
        '1-C22AG3MYKGJWHA',
        '1-C7ABFBTZAPEFLJ',
        '1-C3WBRVJTV72XTX',
        '1-C3LGTP2VTKUFLX',
        '1-C2W2V3BEGKCBN6',
        '1-C25TNGMZNK4CRJ',
        '1-C4JHT633ELECVT',
        '1-C6CJLY6FT6K3NJ',
        '1-C7JAJ7MWJYBBHA',
        '1-CZEJRAMDGFV3RT',
        '1-C7BUGJKZA2AECN',
        '1-C7AZTY2JSBLDEE',
        '1-C6BFJJXJE7VGNE',
        '1-C3L1TFXVTE22E6',
        '1-C34JABJDAYAGSE',
        '1-C4CDA4LFTCMTCA',
        '1-C2TXVCKFHFM2JJ',
        '1-C7LGE6ADABACC6',
        '1-C35KRKLFTN6TV2',
        '1-C6BXC4DTCKAHNJ',
        '1-C7CHR66CV36ZJT',
        '1-CY4XJBLZV7DKAN',
        '1-C7CAV4CXRCAETA',
        '1-C333JP4VKA3XAA',
        '1-C23YVKDXWBNAV2',
        '1-C6KVME5JT24TTT',
        '1-C2UENFKJEPAHR2',
        '1-C3TFNEWUBFBTFE',
        '1-C7DFVF3ZARA3CJ',
        '1-C24UNJDDT3LVTN',
        '1-C6XZSCLETF5WAX',
        '1-C7AVG7B1HA2JT2',
        '1-C4DWGZBGLLDYJ2'
    ) AS t(merchant_id_nk)
),
-- 1. COMMISSION REVENUE (from deliveries/dine out)
commission_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.commission_from_merchant, 0) 
            ELSE 0 
        END) as commission_revenue,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.gross_merchandise_value, 0) 
            ELSE 0 
        END) as gmv,
        COUNT(DISTINCT CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN f.order_id 
        END) as orders
    FROM ocd_adw.f_food_metrics f
    WHERE f.city_id = 13
        AND f.country_id = 1
        AND f.business_type = 0
        AND f.date_id >= 20250501
        AND f.date_id < 20251101
        AND f.merchant_id IN (SELECT merchant_id_nk FROM hon_yi_ni_merchants)
    GROUP BY CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 2. ADS/SPOTLIGHT REVENUE
ads_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(accrued_amount_before_tax_local, 0)) as ads_revenue,
        SUM(COALESCE(billable_ad_spend_local, 0)) as total_ads_spend,
        SUM(COALESCE(mex_prorated_billable_ad_spend_local, 0)) as mex_ads_spend
    FROM ocd_adw.agg_ads_merchant
    WHERE date_id >= 20250501
        AND date_id < 20251101
        AND merchant_id IN (SELECT merchant_id_nk FROM hon_yi_ni_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 3. MEX FUNDED CAMPAIGN REVENUE (spending)
mex_campaign_spend AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(total_mex_promo_spend, 0)) as mex_campaign_spend,
        SUM(COALESCE(total_grab_promo_spend, 0)) as grab_campaign_spend,
        COUNT(DISTINCT merchant_id) as merchants_with_campaigns,
        COUNT(DISTINCT order_id) as campaign_orders
    FROM ocd_adw.f_food_discount
    WHERE city_id = 13
        AND date_id >= 20250501
        AND date_id < 20251101
        AND booking_state_simple = 'COMPLETED'
        AND is_mfp = TRUE
        AND merchant_id IN (SELECT merchant_id_nk FROM hon_yi_ni_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- Combine all revenue sources
combined_revenue AS (
    SELECT 
        COALESCE(c.month_id, a.month_id, m.month_id) as month_id,
        COALESCE(c.commission_revenue, 0) as commission_revenue,
        COALESCE(c.gmv, 0) as gmv,
        COALESCE(c.orders, 0) as orders,
        COALESCE(a.ads_revenue, 0) as ads_revenue,
        COALESCE(a.total_ads_spend, 0) as total_ads_spend,
        COALESCE(a.mex_ads_spend, 0) as mex_ads_spend,
        COALESCE(m.mex_campaign_spend, 0) as mex_campaign_spend,
        COALESCE(m.grab_campaign_spend, 0) as grab_campaign_spend,
        COALESCE(m.merchants_with_campaigns, 0) as merchants_with_campaigns,
        COALESCE(m.campaign_orders, 0) as campaign_orders
    FROM commission_revenue c
    FULL OUTER JOIN ads_revenue a ON c.month_id = a.month_id
    FULL OUTER JOIN mex_campaign_spend m ON COALESCE(c.month_id, a.month_id) = m.month_id
)
SELECT 
    month_id,
    'Hon Yi Ni' as person_name,
    'MGS' as role,
    commission_revenue,
    ads_revenue,
    mex_campaign_spend,
    (commission_revenue + ads_revenue) as total_revenue,
    gmv,
    orders,
    -- Calculate percentages
    ROUND(commission_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as commission_revenue_pct,
    ROUND(ads_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as ads_revenue_pct,
    -- Additional metrics
    total_ads_spend,
    mex_ads_spend,
    grab_campaign_spend,
    merchants_with_campaigns,
    campaign_orders
FROM combined_revenue
ORDER BY month_id;



-- ============================================================================
-- QUERY 4: Revenue Breakdown: Low Jia Ying
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Low Jia Ying (MGS)
-- Last 6 Months (May 2025 - October 2025)
-- ============================================================================

WITH low_jia_ying_merchants AS (
    SELECT merchant_id_nk
    FROM (VALUES '1-CZLBFBBYC7VKLE',
        '1-C3LGN4EHCF2HT2',
        '1-C2C2MBA2NKW3C6',
        '1-C64FSBJWGXTYME',
        '1-C66YC7XUTPMTKE',
        '1-CZEHGFEWAZCZRX',
        '1-CYUBJE3DA3MBAN',
        '1-CY5ZUAVTAE6ATE',
        '1-C34XVBKGVT5UDE',
        '1-C6DHNAWTVCAYTE',
        '1-C34WBAL1WFUAT6',
        '1-C3UZNNXYBALWNN',
        '1-C7ECGJVCDBXWGA',
        '1-C24CVJEJSBKBWE',
        '1-C26KG62URFEJV6',
        '1-C64FSF5WTBA3NT',
        '1-CZDJNNA1CE5GRN',
        '1-CZM2EFAXJKWAGA',
        '1-C26XJ6WAHB4WCT',
        '1-C7AWE7CZJVMAA6',
        '1-C3AXJBNGNJTXMA',
        '1-C2VEJA5XVK51DA',
        '1-C3KVRP6VVBXECX',
        '1-C6KBE4JKE4JJEN',
        '1-C4DGA62YCPJ2RJ',
        '1-C6T2V4MZSB23NT',
        '1-C32TPF3VPBXZLX',
        '1-C2CDAPTVBBVHEA',
        '1-CZLVJT6KAJ5CG2',
        '1-C2DYWA5GAVD2CA',
        '1-C23JT2JVJPVDVN',
        '1-CZDJNNA1CBD2HA',
        '1-C6LBC2XCPFWCRJ',
        '1-C6BCVEXTJKXECJ',
        '1-C2AVPADYTEECTA',
        '1-C23CE6KJAP6DGX',
        '1-C4DJEPC3AGA3BA',
        '1-C4EYNTT2WEJ2L6',
        '1-C2WZJ8L3EXDYAN',
        '1-C62WTTE2CJKWDE',
        '1-C32BGEXEE7UJNN',
        '1-C6UYG653N3KWKE',
        '1-C3BDV4MHCVAYV6',
        '1-CZEHGFEWCJ2VJE',
        '1-CZKUPFKBJ7NGCN',
        '1-C6VKVLEYBE23VA',
        '1-C2MUNU5KCEMGT6',
        '1-C36VGUJBHF2ECE',
        '1-C2XWLYVENVDJWA',
        '1-C3DXVP3YTXA3LX',
        '1-C33HCKE2PBXGME',
        '1-C25FJN3DRJA1NT',
        '1-CZJWLAXGGKKKR6',
        '1-C3DDVNWGBABDTX',
        '1-C6WKBE5BDGAVV6',
        '1-CZEHGFEWAXJDKE',
        '1-C36UCYXHEVD1VE',
        '1-C3VWSEW3LP32CN',
        '1-C6JKVXDWJ3WATE',
        '1-C35UE62FREKVME',
        '1-C3NHDE4FTU5BGA',
        '1-C3MZV4ETAUUENN',
        '1-C6BDLA5EJKXUWE',
        '1-C6KYEJJ1EU2HA6',
        '1-C3WAACNHHB4JTA',
        '1-C4J3TEKYPFLATA',
        '1-C36XTLMZL7K2WE',
        '1-C2X3VK42AKCZWE',
        '1-C2A2J33VNVMJJX',
        '1-C2KFCJ2WAEEGSE',
        '1-C4JXRPN3RULKAE',
        '1-C3VZGP2HE6TKRJ',
        '1-C26WL6WKPCLFRT',
        '1-C3NZA2EUCYAHUA',
        '1-CZLHFBVXJFDKJT',
        '1-C2XTWGKJC3TUBA',
        '1-C3EHTUJWTTW1UA',
        '1-C3NHGAEALXMGCJ',
        '1-C3XFVTUZSE31AE',
        '1-C2UAVGKJL3JBTJ',
        '1-C6AVKB4FBGKXLN',
        '1-C4NCEZEXLLEJBA',
        '1-C3UZNYX1L2UALN',
        '1-C6TWR6CKDA5DRX',
        '1-CZDDHA6FKAUKN6',
        '1-C6UUVZMYA76KAJ',
        '1-C3XZCLJHCTBYTA',
        '1-CZE3L323ACB3EJ',
        '1-C3A2RXACC2AYVX',
        '1-C6VKEZKUT7UTTA',
        '1-C4LGSGBYSAE1JT',
        '1-C2J2V4DVAE2JV2',
        '1-C3DXGBDKLLA1E6',
        '1-C6NWVVM1J8C1WA',
        '1-C3KKCAEHVUTESA',
        '1-C2TZAPKHCEDHJT',
        '1-C2UZNK41C3JUNN',
        '1-C6VWMEAJL233N2',
        '1-C6JFR3TGNP52KA',
        '1-C66KEKTTE36DVN',
        '1-C4DYA662V4A1C6',
        '1-C22YEXWWA4AYGE',
        '1-CZLHFBVXJN5ECE',
        '1-C3VENEW3NAV1TT',
        '1-C2BZTKUUKEJWL2',
        '1-C2BZTKUUJ2BHC6',
        '1-C7MBEP3TPAJGJJ',
        '1-C2JTGJTCA7DTCX',
        '1-C7LZRAA3NE4WWA',
        '1-CYLJTJDBJ63BRE',
        '1-C7DVTTTVRZBKTT',
        '1-C6VHEX2FJ4BYCE',
        '1-C222L7MKAJDAJT',
        '1-C24BEFXVNBJJAJ',
        '1-CZBCPFUJLB2DE6',
        '1-C2WWR8NHE62ERJ',
        '1-C66UTFJ3EBUYEE',
        '1-C2NFLKJZCYMGRN',
        '1-C6E2NCLHNEJBEX',
        '1-CZEFEF5ESE3EHE',
        '1-C2T3RT4XTBUWA2',
        '1-CZEHHAEXFEM2R2',
        '1-C632CF2DUFLASE',
        '1-CZDWTALTLPJUUA',
        '1-C3NHJYXZTB5ELX',
        '1-C3KXJX3HATXCCA',
        '1-C3WHLN5XLZCWR6',
        '1-C3UHFFW1L2NCTN',
        '1-C3DGHE2YJZEKLE',
        '1-C25VFFX2VXA3NE',
        '1-C2WDGXL1NBD2N6',
        '1-C6LGJLMCNANCJJ',
        '1-C4MZUBDANRABRN',
        '1-C25GANW2KF5XA2',
        '1-C33GHAKAFAM1UE',
        '1-C4CCEF5ZR3CBAA',
        '1-C2WYLE5ERCD1SA',
        '1-C36CLLD3NA4DVN',
        '1-C7DBNUNFPE31LN',
        '1-C4LUC32ENFV3GT',
        '1-C4AEUF2YKEW3AX',
        '1-C3L2N4JUKBWWRT',
        '1-C3MKA63AENAHSA',
        '1-C35DJ3BDRU2CVA',
        '1-C3L3RAEYWF2YTN',
        '1-C3D3G23WEKAKGJ',
        '1-C7ACA3E3ALNYR2',
        '1-C2JTLAJWDE6HEX',
        '1-C3LCLLJBVFEHGN',
        '1-C4CXE33CDFBZE2',
        '1-C2KKE8L1DFN1HA',
        '1-C6NWCJE3TETECX',
        '1-C62JNUM3APLFNT',
        '1-C2VKLFL2VFX1UA',
        '1-C7KAG7BUJU4YFA',
        '1-CZK1JRJDR8C2WE',
        '1-C352C63EMBWGAT',
        '1-C3NZAE2EVPNVET',
        '1-C6LVEAEWFEDXJN',
        '1-C3JCMAJZWGCGSA',
        '1-C3LFUCKETCNCVX',
        '1-C25ZMAJUVUNXC6',
        '1-CZDWTALTEJW2ME',
        '1-CZDWTALKVAAHSA',
        '1-C351GY4YSEKJTA',
        '1-CZDEVYUHT7UKA6',
        '1-C3EBTUTVA7T3V2',
        '1-C3K2UAJCAXBUJA',
        '1-C6CHTREEEU2TJE',
        '1-C6JGAE4ZJTNTKE',
        '1-C65DA3NVPFEJL6',
        '1-C6AZT3ECNPD2G6',
        '1-C2MEPEECV3AJCX',
        '1-C4C2LAEAC6EDFA',
        '1-C2WDEB3JDB5TRJ',
        '1-C2CDAPTVC3XKG2',
        '1-C7LANAVGV4LXLA',
        '1-C35FJY5FNU2UEA',
        '1-C7EKEPEBSCBVRN',
        '1-C7K2L4B1JJVWCT',
        '1-C2U1NU3KARDJDA',
        '1-CY5FNLDVVXAEVA',
        '1-C24CTADDCELCDE',
        '1-C3NJE2L1R6NCPA',
        '1-C2XJNJ3JEN3TEN',
        '1-C7BTNFJDCXUBME',
        '1-C251ELKYEYNKGA',
        '1-C7JZA8BHWAAYAX',
        '1-C6LCAE5VRCJ3JT',
        '1-CYTDEXJUNALJKE',
        '1-C2JTGJTCGNJFAJ',
        '1-C2E1LUJEJVEDE6',
        '1-C3ETLNXGHA2TJA',
        '1-C7KETE4AMETFA2',
        '1-C7JWPFJYRFE3LX',
        '1-C7L2RGDATA5JCE',
        '1-C2XAUA6JC2JDV6',
        '1-C353BF3UCJCAGA',
        '1-C4ETME4FGB3URE',
        '1-C3LJL7XTNLE2LT',
        '1-C242FALXL24YRN',
        '1-C62KMFXZNYMXAJ',
        '1-C66DSCNHJAXFSA',
        '1-C3VEETLDVKBFNX',
        '1-C3A3KE4FGP2YLT',
        '1-C7LGLAVZVCLELJ',
        '1-C3ABL72ENATYA2',
        '1-C3KDJE4CLFJYAE',
        '1-C3KWUCJCHCEWLA',
        '1-C7EKEJT2ARMFC6',
        '1-C3WCLTLKGJX1LJ',
        '1-C2XCE7VCUFKAGN',
        '1-C32DC6X2VZJ2VT',
        '1-C6N3CA3GATBVE6',
        '1-C33HJKKDLVNFJ6',
        '1-C7ABE64JLKL2RX',
        '1-C7MBEP3TG7MAJN',
        '1-C7LERGKZWE2AA6',
        '1-C7LFHFMJCTTVME',
        '1-CZCTGF3JGCJEG6',
        '1-C2XFTRMDLETHNN',
        '1-C2VEGT5UEBVGKE',
        '1-C6LBDFW3TVCXVT',
        '1-C7MBCVMAN2UAG6',
        '1-C6NYPEN3NJV1TN',
        '1-C23ETK6XAJVBKE',
        '1-C33GGUKCMCCFRX',
        '1-C3W3TEAVG2MWCT',
        '1-C3CZSEEAKBEVGN',
        '1-C7KYVRBALRLTVA',
        '1-C3NKL64GL2AHLX',
        '1-C22DRT3HVNBJEX',
        '1-C63JPFX3R3A1GJ',
        '1-C2KXN4CCTBUHJX',
        '1-CZK1JRJDWEDTNE',
        '1-C2XALEKJGF4XJA',
        '1-C3KDJE4CLRKCGE',
        '1-C2WXANKJVLNTHE',
        '1-C4JEJ23UCF2ZC2',
        '1-C6BEME2VVXTAKE',
        '1-C2XAPENTAYL2AJ',
        '1-C7L3FECUG4JHJA',
        '1-C3UBRFXAPE6FNJ',
        '1-C7L3GE2JRUBKTN',
        '1-C2XGTENJMELYLN',
        '1-C66KEE4ECT4TSE',
        '1-C4K3T2WBJUJWTE',
        '1-C7EKGTVHRKVGA6',
        '1-C2TJAFW3AKV2EE',
        '1-C7LCTX2FDETVMA',
        '1-C4LWLT3JVVBYR6',
        '1-C4CJWBMUNYM2DE',
        '1-C3WDV4DZAK53AE',
        '1-C2WXANL1JE21LN',
        '1-C2VEE2B3GE4ZL2',
        '1-C2ADHCCVC2XHGX',
        '1-C3NXA4DGLJXZCA',
        '1-C7AGJJTXJPEWNT',
        '1-C7LCTJ2VA3EAEX',
        '1-C3WANUK1JLEARN',
        '1-C23ETK5ATE3JV2',
        '1-C7LZRAA3MAU3NJ',
        '1-C7ADSAJHTJUKR6',
        '1-C4JZJFCALZMJLT',
        '1-C62JNZBUEBAKR6',
        '1-C65DVYAERFTAG2',
        '1-C242GLEWNUCJR2',
        '1-C3TKN4DVTEMEKE',
        '1-C6W2HE3DN6BZGJ',
        '1-C3TKN4DVT6DDJX',
        '1-C7ADVAKTJFAYDE',
        '1-C7JTCANBPGMXJA',
        '1-C7MBBEXYVYNGCN',
        '1-C3DKA4MFMFU3GJ',
        '1-C32CEPXVDCEYGA',
        '1-C3LFWBE3C26JTN',
        '1-C3VCRTE2FE3CDA',
        '1-C3UTLKKEG3KCLE',
        '1-C3XBLALGNLDKTN',
        '1-C32HKE3TWFEHVA',
        '1-C26KL3KFPGAFC6',
        '1-C351KCLWNBCEAX',
        '1-C3KBLGAEFBTFET',
        '1-C7A1LJ3ZLGCZCX',
        '1-C7D1BCDYL3UGHA',
        '1-C3UBRTJUBFUGSE',
        '1-C4EDRVNJLA5TEJ',
        '1-C3BFN6CYPFM2RE',
        '1-C7LDNBVYE7UACE',
        '1-C7L1LAXYVBL3TX',
        '1-C3XJGF2UTJLZR6',
        '1-C222NU3JTAKGL2',
        '1-C26WSAXGUCABTN',
        '1-C35ZLTUJSGAKEX',
        '1-C3X1VBE2E8DKVJ',
        '1-C3TBCPWGVAUAL6',
        '1-C7D1FBJYBE52V2',
        '1-C24WEBKXVE5CGT',
        '1-C3DXV6X1RNUAVJ',
        '1-C3BTVBJXV6VZPE',
        '1-C3NBE732J6TZAN',
        '1-C7K3N7CAEZMCTT',
        '1-C4A3NULCVLKWEA',
        '1-C2BJCXLHE25JC6',
        '1-C6V3HGJUTNDDME',
        '1-C7E1BFMKHFBHRN',
        '1-C3KBLGAEG2UZTE',
        '1-C26KJJDFATDEC2',
        '1-CZDKECDXL7V1A2',
        '1-C6TWNJAYAPUDEA',
        '1-C6KVLEKHMAXGGT',
        '1-C4MVC8C3JUBELA',
        '1-C6UFAYDJAX6AG2',
        '1-C6VXJNB2J2CKGX',
        '1-C4NDVXDWLLK3ME',
        '1-CZDWTALTTU3GTN',
        '1-C3KJJ4MKGUXBSA',
        '1-C2UFL23KGPUVAJ',
        '1-C3E1GVKZME5WLA',
        '1-CZDWTALUC3C1LX',
        '1-C3E3TY3EV6ETC6',
        '1-C632E2UTSAWXLX',
        '1-C3NBCPAFE3AENX',
        '1-C36HBCKGRCNJRT'
    ) AS t(merchant_id_nk)
),
-- 1. COMMISSION REVENUE (from deliveries/dine out)
commission_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.commission_from_merchant, 0) 
            ELSE 0 
        END) as commission_revenue,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.gross_merchandise_value, 0) 
            ELSE 0 
        END) as gmv,
        COUNT(DISTINCT CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN f.order_id 
        END) as orders
    FROM ocd_adw.f_food_metrics f
    WHERE f.city_id = 13
        AND f.country_id = 1
        AND f.business_type = 0
        AND f.date_id >= 20250501
        AND f.date_id < 20251101
        AND f.merchant_id IN (SELECT merchant_id_nk FROM low_jia_ying_merchants)
    GROUP BY CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 2. ADS/SPOTLIGHT REVENUE
ads_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(accrued_amount_before_tax_local, 0)) as ads_revenue,
        SUM(COALESCE(billable_ad_spend_local, 0)) as total_ads_spend,
        SUM(COALESCE(mex_prorated_billable_ad_spend_local, 0)) as mex_ads_spend
    FROM ocd_adw.agg_ads_merchant
    WHERE date_id >= 20250501
        AND date_id < 20251101
        AND merchant_id IN (SELECT merchant_id_nk FROM low_jia_ying_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 3. MEX FUNDED CAMPAIGN REVENUE (spending)
mex_campaign_spend AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(total_mex_promo_spend, 0)) as mex_campaign_spend,
        SUM(COALESCE(total_grab_promo_spend, 0)) as grab_campaign_spend,
        COUNT(DISTINCT merchant_id) as merchants_with_campaigns,
        COUNT(DISTINCT order_id) as campaign_orders
    FROM ocd_adw.f_food_discount
    WHERE city_id = 13
        AND date_id >= 20250501
        AND date_id < 20251101
        AND booking_state_simple = 'COMPLETED'
        AND is_mfp = TRUE
        AND merchant_id IN (SELECT merchant_id_nk FROM low_jia_ying_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- Combine all revenue sources
combined_revenue AS (
    SELECT 
        COALESCE(c.month_id, a.month_id, m.month_id) as month_id,
        COALESCE(c.commission_revenue, 0) as commission_revenue,
        COALESCE(c.gmv, 0) as gmv,
        COALESCE(c.orders, 0) as orders,
        COALESCE(a.ads_revenue, 0) as ads_revenue,
        COALESCE(a.total_ads_spend, 0) as total_ads_spend,
        COALESCE(a.mex_ads_spend, 0) as mex_ads_spend,
        COALESCE(m.mex_campaign_spend, 0) as mex_campaign_spend,
        COALESCE(m.grab_campaign_spend, 0) as grab_campaign_spend,
        COALESCE(m.merchants_with_campaigns, 0) as merchants_with_campaigns,
        COALESCE(m.campaign_orders, 0) as campaign_orders
    FROM commission_revenue c
    FULL OUTER JOIN ads_revenue a ON c.month_id = a.month_id
    FULL OUTER JOIN mex_campaign_spend m ON COALESCE(c.month_id, a.month_id) = m.month_id
)
SELECT 
    month_id,
    'Low Jia Ying' as person_name,
    'MGS' as role,
    commission_revenue,
    ads_revenue,
    mex_campaign_spend,
    (commission_revenue + ads_revenue) as total_revenue,
    gmv,
    orders,
    -- Calculate percentages
    ROUND(commission_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as commission_revenue_pct,
    ROUND(ads_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as ads_revenue_pct,
    -- Additional metrics
    total_ads_spend,
    mex_ads_spend,
    grab_campaign_spend,
    merchants_with_campaigns,
    campaign_orders
FROM combined_revenue
ORDER BY month_id;



-- ============================================================================
-- QUERY 5: Revenue Breakdown: Lee Sook Chin
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Lee Sook Chin (MGS)
-- Last 6 Months (May 2025 - October 2025)
-- ============================================================================

WITH lee_sook_chin_merchants AS (
    SELECT merchant_id_nk
    FROM (VALUES '1-C2W2RZKJJTT1A6',
        '1-C3AWL3MDLEU2LN',
        '1-C2WDNA3JN73WDE',
        '1-C2NBV7NJNT4YTE',
        '1-C3EVFF3UPF4XEX',
        '1-C3LBJ3EWCBATLT',
        '1-C34XCAKTRYAUTJ',
        '1-C3KCJ3KWVZA3T2',
        '1-C3TVE63TMF2TGX',
        '1-C3VGTNXUA34YRX',
        '1-C2TDLYWDV353JE',
        '1-C7KJGBUAGAABNE',
        '1-C2EBAJA3EFLDJT',
        '1-C2WJL6TXWE6ERJ',
        '1-C3LCJJEEL2WJGX',
        '1-C24UGXDVNJAGNJ',
        '1-C65KGTMTWFKCVX',
        '1-C63WABU3CX5DET',
        '1-C3UUGLEEDAMGSA',
        '1-C3KBN7DAGYDVEX',
        '1-C22KAZL1RX6GDE',
        '1-C3U2GVEUAAJCV6',
        '1-C23HGU3KTXLTV2',
        '1-C3KCJ7XHGJ3XKA',
        '1-C3W3VTEVNU4JRN',
        '1-C3UFDF3WSFWKJ2',
        '1-C2XCJJBEFFXFHA',
        '1-C22GLRNGEA4ART',
        '1-C3U2GVETVTAYCJ',
        '1-C23JJ6DJLKCGJE',
        '1-C4BZELLKKGMCWE',
        '1-C23TACDEKANGNX',
        '1-C32KALK1NTACJA',
        '1-C7DZKECFJY3DEN',
        '1-C3DZAYCEHBWGN2',
        '1-C3DBEN4VGBETTX',
        '1-C2MAL75TKCDUMA',
        '1-C3UTEP5YPGK2SE',
        '1-C2WZJ8NHRJ6AR2',
        '1-C3EUKE2GJ6NBVT',
        '1-C33ZRVKCJTLYJJ',
        '1-C4EGC7UTKA6BJX',
        '1-C3NBETJGA2UCTA',
        '1-C2KWTELTJ7DHHE',
        '1-C22VA2UUGE2ELE',
        '1-C34XVBKGVENVGX',
        '1-C4LUEAXZCF5XUE',
        '1-C35GCA4FRANCNT',
        '1-C6WVMGC3TTCEJT',
        '1-C23DT36JA3KCKE',
        '1-C3LFPBKWLT4CTT',
        '1-C4CETY22VZN3LX',
        '1-C7K3L7V3SE6EFE',
        '1-C2XFRT5CCABDNE',
        '1-C22YEBDCFBKGGJ',
        '1-C4JGAY6JRNAEV6',
        '1-C62KNTWYAJAGEE',
        '1-C2XCJ33JG7VDCJ',
        '1-C7MEL32VLX3XUA',
        '1-C3EACGJHE6L2V6',
        '1-C3CTTXAYWEKARE',
        '1-C2WZE7KJJF33T2',
        '1-C7MXRJ3ZEJCGCJ',
        '1-C4CZCKJHJZNEJN',
        '1-C3TACT3CHGETUA',
        '1-C3KTG6X3NJETSE',
        '1-C3NHJCJXJAMEN2',
        '1-C3UTMF5WUALYGX',
        '1-C2WZERN1JANVLN',
        '1-C3D3FEJEGK6ZGE',
        '1-C3DWC2W3HEUCC2',
        '1-C2WGRAA1GNMJDE',
        '1-C2XAVT3JEZCBC2',
        '1-C7L1LAXYTAATT6',
        '1-C25AVNXDUGAHEE',
        '1-C32KHCDHTAAGVE',
        '1-C243BGBEJ4L1L2',
        '1-C7JKEX3HA6UVGX',
        '1-C3WHN3JWALJTNN',
        '1-C36VAN2WCUVYV2',
        '1-C4CKV4KEVXDTBE',
        '1-C4JUCPBYJVDWA2',
        '1-C35EE3E3R7D3WE',
        '1-C25TNFTXTLEZTN',
        '1-C7K2RKTBEFXKRJ',
        '1-C3M1N72XNRJ1AT',
        '1-C4CERVE1AP23FE',
        '1-C3CEMF5BTEEGR6',
        '1-C6NTG62HNFNHCA',
        '1-C2VZNT3JBFLWPE',
        '1-C3CCCANCECNVGN',
        '1-C7EDGGMXLPBUGX',
        '1-C3ETLZMHJTBCVX',
        '1-C3LAPAJJRP2HLX',
        '1-C25KLALHMBMTRX',
        '1-C3ETLJMZR7L3CN',
        '1-C4NBG6XCBE3KA2',
        '1-C3EUE3JZN2TFKA',
        '1-C2XUC36JLJAKGA',
        '1-C2WWUB3JCFE3RN',
        '1-C4DJCFC3CVDFCE',
        '1-C3VXLPW3WEJWL6',
        '1-C3KBTLDJGNKALX',
        '1-C22ZTPVXEUTEVE',
        '1-C3D2L64DSB6UTN',
        '1-C2W2V25ANJA3EN',
        '1-C3UGBF5HFCBJNE',
        '1-C36VTP3EWCKHVJ',
        '1-C4NCEP3WCEMZUA',
        '1-C3ETME4ZJENHGJ',
        '1-C22GNU3JAPTDVA',
        '1-C3LFPBKWL3EJE6',
        '1-C3CJC2J3TJMTME',
        '1-C3XTV6JWSE3KME',
        '1-C2XVLANYNBCGVE',
        '1-C3MZWAEGL8JKUE',
        '1-C3MEA2XCC3KGJX',
        '1-CZJTV33WLB2TJA',
        '1-C33UJUEUVTUECA',
        '1-C3CKTLKUT4DUSA',
        '1-C2WCGU3CBCJHRE',
        '1-C3D3GKUAL363L2',
        '1-C3LBLYXATADVVN',
        '1-C23HDCD1E2CKJE',
        '1-C3NZAKKBT4MCPE',
        '1-C2J3C3ATJ66HG2',
        '1-C2VKGEKJLRAZVE',
        '1-C3ETME4ZG6VFCJ',
        '1-C6XHA4LJCBAAEJ',
        '1-C3KDGTDZRNDVTT',
        '1-C3EAVEDKJX62KA',
        '1-C23BWGB2TUTGRJ',
        '1-C33GFF2FJTN2RJ',
        '1-C2W2RENUERBDNE',
        '1-C32ECJJXCPTYJJ',
        '1-C3M2LBEDAXBHGJ',
        '1-C2WWLRKJLXBCGT',
        '1-C3CDA2DUTNEJGN',
        '1-C2XGPAAXCN4XV6',
        '1-C3CDVE4TJY5WHA',
        '1-C4MFT753SBBJJE',
        '1-C3E1LLMZA2AAEX',
        '1-C7DFEUJ1ETMGSA',
        '1-C22YDE5TGGMKRX',
        '1-C3KTG6X3G7CJWA',
        '1-C25ATADFNXTFKE',
        '1-C2WWLRNGWFUDTA',
        '1-C2XWL8KHRAAEJ2',
        '1-C3CJVF4XNKA1FE',
        '1-C3EACGJHJGLKKA',
        '1-C3MKVP2VCXCXC6',
        '1-C3E2CX3EKB2XET',
        '1-C2WXTZL2JEJYJX',
        '1-C7L1J741VEKHSA',
        '1-C23ZNUDUNA61GT',
        '1-C35GVX3DKA2GWE',
        '1-C4JFT76KEKKVGA',
        '1-C3D2L64DT72KVJ',
        '1-C3D3FEJEAT4ZR2',
        '1-C3EBBEAHE3WGT2',
        '1-C222L3A1L4BJCT',
        '1-C4KXNYUYDBL3L2',
        '1-CZJ2AXW3TCCDVX',
        '1-C3KDJALBAYMVV6',
        '1-C66HEZA3L3B1AX',
        '1-C4NCEP3WDAETCX',
        '1-C36TJVKKNEVYAA',
        '1-C2XFRNKJDGAJV6',
        '1-C4NCEP3WCBUUG2',
        '1-C4EEJJUDNYXGFA',
        '1-C23YCNWYFA32C6',
        '1-C3DZBEBWEVMGET',
        '1-C2NKT3XDKA3GT2',
        '1-C7J2NKMALPEJAN',
        '1-C3KBRN6ZPFWDL2',
        '1-C3MVLB6FKFLYMA',
        '1-C4MZV76KRJBXNT',
        '1-C6VBJVAGBBXGJA',
        '1-CZJ2L8NGWGABRT',
        '1-C6JTCNMVNBCAPE',
        '1-C4L2JBEBCCEZGA',
        '1-C3MJWCDXCNEZAN',
        '1-C7EXG7MHNA3DPA',
        '1-C2XGR7NYAGKFHA',
        '1-C7KVMEC3GNKHJ2',
        '1-C3EWDBKGUBMCVT',
        '1-C65DA3NVLTEUJT',
        '1-C6AHE3VJSENFEX',
        '1-C7MVFF2BG7AACT',
        '1-C3MZEAEYLPNALX',
        '1-C3NJEE2HRCEUHE',
        '1-C3MZT2EKLADUA2',
        '1-C3D2FB2ZT74UET',
        '1-C4NBEGBCANDCEJ',
        '1-C3DXAYJHAUCXJT',
        '1-C3AWMCMACTTFE6',
        '1-C3XANP5FCXDVGA',
        '1-C3EBAF4UMAUYRE',
        '1-C2WZHBDTC2TKPE',
        '1-C3EBR7EDPCJYV2',
        '1-C4JCLTVFAP3FR6',
        '1-C3KHTTLGNPLCE2',
        '1-C3EVHAKTC7TCRJ',
        '1-C7KBGPMZNPCYBA',
        '1-C3M1UFB3J2MDTJ',
        '1-C341MA5FFCBDKE',
        '1-C3CYTLJKJU2VC6',
        '1-C3NCCFXUV7BKNX',
        '1-C3AWNK62KBT1KA',
        '1-C3MZTAEZGJXJLX',
        '1-C36GEKLBTXKACT',
        '1-C3JTJLEZLKKEKA',
        '1-C3TCBBNFNFKFGX',
        '1-C7LJGXNEAB4AHE',
        '1-C3LFT7XXT6CELX',
        '1-C3CDSE5JLE5WCJ',
        '1-C3EWA76CMENUEJ',
        '1-C3NXE3NBC7T3RX',
        '1-C3WWRE2UEZDHC6',
        '1-C3VGV3EVFCL2CA',
        '1-C4AFVTJHRENXSA',
        '1-C3MZUBJVLRNZAJ',
        '1-C26JJ63KNFJYRN',
        '1-C243CUJHUAWEEX',
        '1-C3KJNEAZG8NXEE',
        '1-C3DYCPDTVNCZRA',
        '1-C22DRCNAWA3ZRE',
        '1-C23BWGL1GEEDRE',
        '1-C6TFC2VZRRCVFE',
        '1-C4KXNYUZLY3ZEJ',
        '1-C7LDLK23EB4ZJA',
        '1-C4ADCUKDHBBAAJ',
        '1-C3LGRGJTN6WJLX',
        '1-C22ZTPWDRY32RX',
        '1-C7CVVZCCKF5WAX',
        '1-C3CJEJLAWBCFRA',
        '1-C3MKWBDHWCEKNJ',
        '1-C7LVN64HBEWUNX',
        '1-C6TVTRCEAF2KGJ',
        '1-C3KTAE5GG2XJMA',
        '1-C7CVVZCDLFTCA2',
        '1-C2UATELYR26HGX',
        '1-C7M3E6WWECBXJT',
        '1-C2X2VT3JLY5TVX',
        '1-C4NXCTTVA4NYV6',
        '1-C6TEC2LUET5KGX',
        '1-C22AGU6WAUA1LA',
        '1-C2XBKA3VLN33LA',
        '1-C4LZWF4XKA2KN6',
        '1-CZKUPFKBJJ41V6',
        '1-C3UEGNXELEXTWE',
        '1-C3NBCPAEGCAYV2',
        '1-C3KHR4KAVF4HEA',
        '1-C3N3FCEKC2MHT6',
        '1-C4AARUUZGRLFEE',
        '1-C7NAEB3VRELKG6',
        '1-C3DZAYCELVBGAA',
        '1-C25KLVEWSBJYN6',
        '1-C7ACBCMTPB2GVE',
        '1-C4JTGNAYE2LDJ6',
        '1-C3UVWFWVJAMKGT',
        '1-C3DZC2JKJ3JYJX',
        '1-C3D2RF2HE3BAT6',
        '1-C3DBVFLTGCE1EJ',
        '1-C35VVTEXGVETAE',
        '1-C3EWECJEJKKVRJ',
        '1-C2XUC33JLTLGUE',
        '1-C3L1C4JJE73GN6',
        '1-C2WYLEDFCB52L6',
        '1-C3NBDE2KGBM3LA',
        '1-C3W2WE3DEVLJVE',
        '1-C3BHKBL2JGM3JN',
        '1-C3EACYCGNJ5KCJ',
        '1-C3KCJ3KWVZBAVA',
        '1-C3UUJKJJEUUET2',
        '1-C7KKRF22NKECCN',
        '1-C2WZJB3JAZCJPA',
        '1-C4LFVKNXGYTKEN',
        '1-C2XWN6NACEEBLX',
        '1-C6XJV75KLRL3JJ',
        '1-C25VEXBGEXNVEX',
        '1-C7MBG2EXVAJJUE',
        '1-C3UZJTEUFFC2VE',
        '1-C66WGTXBN8LHEE',
        '1-C3M1V7W3A8C2AN',
        '1-C3CTTAEVE2J2LJ',
        '1-C7LDC6NYJKKZA2',
        '1-C3DKPANATT3EAN',
        '1-C221SA42LXA1RN',
        '1-C7M2GALARYEVR6',
        '1-C3KEHF3XUGJ3RA',
        '1-C7DHTXVZEJT3JN',
        '1-C3EVCF4FSADVT2',
        '1-C34FHCJCJUXGEA',
        '1-C3CJVF4XLT5HRX',
        '1-C3XEAUJCC4LCPE',
        '1-C2XUC33JJJNUL2',
        '1-C3X3RTKDV7NFSA',
        '1-C2NKVRC1AB6HRX',
        '1-C3DKNY2HNXLWCA',
        '1-C4A1UAMKNFEDLJ',
        '1-C2WJL6MCLU22GT',
        '1-C6T2DEJUL7NBE6',
        '1-C3CCAF5BTFKFTT',
        '1-C3UFGBETA3UHNJ',
        '1-C3KTE3EEJB5KMA',
        '1-C3MZWFBVLNCCLA',
        '1-C2UBJ6KHEYCWE6',
        '1-C3BURY3UNU52L2',
        '1-C6MFEY3ABCLTGX',
        '1-C633RRDXGJJZAJ',
        '1-C3CJCXTWJ6AVV2',
        '1-C3ETJ2EYPEKYDA',
        '1-C3WEC2EUE732VA',
        '1-C2W2REKJACKDCE',
        '1-C2VJSGLVPE4FEJ',
        '1-C65YJA5AV64TCJ',
        '1-C3TFL7XANX53JA',
        '1-C6WALK5VJYBASA',
        '1-C26KLTVTPEEDVX',
        '1-C2DCV7UDLXMYVE',
        '1-C3DZAYCEJKMECT',
        '1-C3DHCKMJG7VHPE',
        '1-C3VKG72UBBXCLN',
        '1-CZJ3L7BHKFEEA2',
        '1-C3EBBEAHHCKGFE',
        '1-C3VKNF3GCCEHLA',
        '1-C4MKWE61R3BJCN',
        '1-C26UEN2JEETBSA'
    ) AS t(merchant_id_nk)
),
-- 1. COMMISSION REVENUE (from deliveries/dine out)
commission_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.commission_from_merchant, 0) 
            ELSE 0 
        END) as commission_revenue,
        SUM(CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN COALESCE(f.gross_merchandise_value, 0) 
            ELSE 0 
        END) as gmv,
        COUNT(DISTINCT CASE 
            WHEN f.booking_state_simple = 'COMPLETED' 
            THEN f.order_id 
        END) as orders
    FROM ocd_adw.f_food_metrics f
    WHERE f.city_id = 13
        AND f.country_id = 1
        AND f.business_type = 0
        AND f.date_id >= 20250501
        AND f.date_id < 20251101
        AND f.merchant_id IN (SELECT merchant_id_nk FROM lee_sook_chin_merchants)
    GROUP BY CAST(SUBSTRING(CAST(f.date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 2. ADS/SPOTLIGHT REVENUE
ads_revenue AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(accrued_amount_before_tax_local, 0)) as ads_revenue,
        SUM(COALESCE(billable_ad_spend_local, 0)) as total_ads_spend,
        SUM(COALESCE(mex_prorated_billable_ad_spend_local, 0)) as mex_ads_spend
    FROM ocd_adw.agg_ads_merchant
    WHERE date_id >= 20250501
        AND date_id < 20251101
        AND merchant_id IN (SELECT merchant_id_nk FROM lee_sook_chin_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- 3. MEX FUNDED CAMPAIGN REVENUE (spending)
mex_campaign_spend AS (
    SELECT 
        CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER) as month_id,
        SUM(COALESCE(total_mex_promo_spend, 0)) as mex_campaign_spend,
        SUM(COALESCE(total_grab_promo_spend, 0)) as grab_campaign_spend,
        COUNT(DISTINCT merchant_id) as merchants_with_campaigns,
        COUNT(DISTINCT order_id) as campaign_orders
    FROM ocd_adw.f_food_discount
    WHERE city_id = 13
        AND date_id >= 20250501
        AND date_id < 20251101
        AND booking_state_simple = 'COMPLETED'
        AND is_mfp = TRUE
        AND merchant_id IN (SELECT merchant_id_nk FROM lee_sook_chin_merchants)
    GROUP BY CAST(SUBSTRING(CAST(date_id AS VARCHAR), 1, 6) AS INTEGER)
),
-- Combine all revenue sources
combined_revenue AS (
    SELECT 
        COALESCE(c.month_id, a.month_id, m.month_id) as month_id,
        COALESCE(c.commission_revenue, 0) as commission_revenue,
        COALESCE(c.gmv, 0) as gmv,
        COALESCE(c.orders, 0) as orders,
        COALESCE(a.ads_revenue, 0) as ads_revenue,
        COALESCE(a.total_ads_spend, 0) as total_ads_spend,
        COALESCE(a.mex_ads_spend, 0) as mex_ads_spend,
        COALESCE(m.mex_campaign_spend, 0) as mex_campaign_spend,
        COALESCE(m.grab_campaign_spend, 0) as grab_campaign_spend,
        COALESCE(m.merchants_with_campaigns, 0) as merchants_with_campaigns,
        COALESCE(m.campaign_orders, 0) as campaign_orders
    FROM commission_revenue c
    FULL OUTER JOIN ads_revenue a ON c.month_id = a.month_id
    FULL OUTER JOIN mex_campaign_spend m ON COALESCE(c.month_id, a.month_id) = m.month_id
)
SELECT 
    month_id,
    'Lee Sook Chin' as person_name,
    'MGS' as role,
    commission_revenue,
    ads_revenue,
    mex_campaign_spend,
    (commission_revenue + ads_revenue) as total_revenue,
    gmv,
    orders,
    -- Calculate percentages
    ROUND(commission_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as commission_revenue_pct,
    ROUND(ads_revenue * 100.0 / NULLIF((commission_revenue + ads_revenue), 0), 2) as ads_revenue_pct,
    -- Additional metrics
    total_ads_spend,
    mex_ads_spend,
    grab_campaign_spend,
    merchants_with_campaigns,
    campaign_orders
FROM combined_revenue
ORDER BY month_id;



-- ============================================================================
-- QUERY 6: Revenue Breakdown: Darren (Template)
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Darren (AM)
-- Note: Run Part 1 query first to get merchant IDs, then update this query
-- ============================================================================

-- TODO: Replace merchant_ids with actual IDs from Part 1 query
SELECT 
    'Run Part 1 query first to get merchant IDs for Darren' as note;



-- ============================================================================
-- QUERY 7: Revenue Breakdown: Suki (Template)
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Suki (AM)
-- Note: Run Part 1 query first to get merchant IDs, then update this query
-- ============================================================================

-- TODO: Replace merchant_ids with actual IDs from Part 1 query
SELECT 
    'Run Part 1 query first to get merchant IDs for Suki' as note;



-- ============================================================================
-- QUERY 8: Revenue Breakdown: Chia Yee (Template)
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Chia Yee (AM)
-- Note: Run Part 1 query first to get merchant IDs, then update this query
-- ============================================================================

-- TODO: Replace merchant_ids with actual IDs from Part 1 query
SELECT 
    'Run Part 1 query first to get merchant IDs for Chia Yee' as note;



-- ============================================================================
-- QUERY 9: Revenue Breakdown: Hsin Tsi Lim (Template)
-- ============================================================================


-- ============================================================================
-- REVENUE BREAKDOWN: Hsin Tsi Lim (AM)
-- Note: Run Part 1 query first to get merchant IDs, then update this query
-- ============================================================================

-- TODO: Replace merchant_ids with actual IDs from Part 1 query
SELECT 
    'Run Part 1 query first to get merchant IDs for Hsin Tsi Lim' as note;



-- ============================================================================
-- QUERY 10: Combined Summary
-- ============================================================================


-- ============================================================================
-- COMBINED REVENUE SUMMARY (All Individuals)
-- ============================================================================

-- This will combine results from all individual queries
-- Run all individual queries first, then combine results

SELECT 
    'Run individual queries first, then combine results' as note;


